-- ============================================================
-- Migración: Unidades de negocio Veolia + campos en afiliados
-- ============================================================

CREATE TABLE IF NOT EXISTS veolia_unidades_negocio (
  id      INT UNSIGNED   NOT NULL AUTO_INCREMENT,
  nombre  VARCHAR(300)   NOT NULL,
  activo  TINYINT(1)     NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO veolia_unidades_negocio (nombre) VALUES
  ('AGUAS DE LA SABANA S.A. E.S.P'),
  ('EMPRESA METROPOLITANA DE ASEO DE PASTO S.A. ESP'),
  ('EMPRESA METROPOLITANA DE ASEO DEL PUTUMAYO SAS ESP'),
  ('EMPRESA METROPOLITANA DE ASEO S.A. E.S.P EMAS SEPTICLEAN'),
  ('EMPRESA METROPOLITANA DE ASEO S.A. E.S.P EMAS-MANIZALEZ'),
  ('EMPRESA METROPOLITANA DE ASEO CHINCHINA S.A E.S.P'),
  ('TECNOLOGIAS AMBIENTALES DE COLOMBIA S.A. E.S.P -BOGOTA'),
  ('VE SERVICIOS DE EFICIENCIA ENERGETICA S.A.S'),
  ('VEOLIA AGUAS DE COROZAL SAS E.S.P'),
  ('VEOLIA AGUAS DE LA GUAJIRA S.A.S E.S.P'),
  ('VEOLIA AGUAS DE MONTERIA S.A. E.S.P'),
  ('VEOLIA AGUAS DE SINCELEJO S.A.S E.S.P'),
  ('VEOLIA AGUAS DE TUNJA S.A. E.S.P.'),
  ('VEOLIA ASEO BUGA S.A E.S.P'),
  ('VEOLIA ASEO CALI S.A. E.S.P'),
  ('VEOLIA ASEO PALMIRA S.A. E.S.P'),
  ('VEOLIA ASEO PRADERA S.A. E.S.P.'),
  ('VEOLIA ASEO SANTANDER Y CESAR S.A E.S.P.'),
  ('VEOLIA ASEO SUR OCCIDENTE S.A. E.S.P.'),
  ('VEOLIA ASEO TULUA S.A E.S.P'),
  ('VEOLIA COLOMBIA S.A.S. E.S.P. - CÚCUTA'),
  ('VEOLIA COLOMBIA S.A.S. E.S.P. - YOPAL'),
  ('VEOLIA COLOMBIA S.A.S. E.S.P. -HOLDING'),
  ('VEOLIA CONSULTING COLOMBIA S.A.S ESP'),
  ('VEOLIA SERVICIOS INDUSTRIALES COLOMBIA S.A.S. E.S.P'),
  ('VEOLIA SERVICIOS INDUSTRIALES DE COLOMBIA S.A.S E.S.P.- SUCURSAL CARTAGENA');

ALTER TABLE afiliados
  ADD COLUMN unidadNegocio VARCHAR(300) NULL DEFAULT NULL AFTER nombreEmpresa,
  ADD COLUMN planVeolia    ENUM('PLATINO','ORO') NULL DEFAULT NULL AFTER unidadNegocio;
